### ISSUE TITLE
example of configuration?

### ISSUE THREAD

**Issue by andyparsons** [ring-clojure/ring-defaults#11]
Hi- we're using ring-defaults and woul like to turn on ssl-redirects but it's not clear how to override default configuration. Does a config map get passed into ring defaults?

**Comment by weavejester** [comment]
Yes; that's its argument. As the README says:

> The default configurations are just maps of options

**Comment by andyparsons** [comment]
Understood and thanks. Perhaps for the uninitiated a quick example might be helpful in the README.

**Comment by weavejester** [comment]
Well, there's one example there already:

```clojure
(assoc secure-site-defaults :proxy true)
```

I guess I could add another one in.
