### ISSUE TITLE
api-defaults will set content-types automatically which is incompatible with wrap-json-response

### ISSUE THREAD

**Issue by jiacai2050** [ring-clojure/ring-defaults#20]
I think most of developers will meet this issue, and solution to this issue is simple after I dig into src of both [wrap-json-response](https://github.com/ring-clojure/ring-json/blob/master/src/ring/middleware/json.clj#L106) and [api-defaults](https://github.com/ring-clojure/ring-defaults/blob/master/src/ring/middleware/defaults.clj#L27)

Is it more reasonable to set content-types default to false in api-defaults or add an option to set content-type forcefully in wrap-json-response ?

**Comment by weavejester** [comment]
Sorry, I don't understand what you're trying to say. Did you mean "**in**compatible", and if so, why is it incompatible? `wrap-content-types` won't set the content type if its already been set by other middleware.

**Comment by jiacai2050** [comment]
Oh, sorry. It's "incompatible". I already updated the title.

I will show some codes to reproduce the incompatible issue.

```
(def app
  (-> handler
      (wrap-defaults api-defaults)
      wrap-json-response))
```
If I define `app` like above, `wrap-json-response` will not work, because `Content-Type` is already set in `wrap-defaults`.

I can work around this simply by switching the order of the two middlewares, but demos I search from google always put `wrap-defaults` or `handler/api` or `handler/site` at first then other middlewares. Orders of middleware do matter a lot than I think at first, so in order to be newbie-friendly, `ring-defaults` can do something like I said in first comment

**Comment by weavejester** [comment]
`wrap-defaults` should typically be the outermost middleware applied. I can add a note to the README to emphasize that.

**Comment by jiacai2050** [comment]
documents is less useful than defaults. 

From my point of view, `api-defaults` should make sure response is in json format. is it more reasonable to add `wrap-json-response` in `api-defaults` ?

**Comment by weavejester** [comment]
No, because an API is not necessarily going to return JSON, and because `wrap-defaults` needs to be the outermost middleware for other reasons. For example, `wrap-params` is part of `wrap-defaults`, and consumes the body InputStream.

**Comment by jiacai2050** [comment]
Got your point.

<img width="1105" alt="how ring middleware work" src="https://cloud.githubusercontent.com/assets/3848910/21600276/4c2c4a38-d1b4-11e6-9886-926fb0846122.png">

For your convenience, I have draw a flow chart to demo how middlewares work

**Comment by weavejester** [comment]
Thanks for the diagram, but the Ring-Defaults library isn't the place to be explaining middleware. The Ring wiki might be a better choice. However, diagrams are also both a little inaccurate, I'm afraid.

**Comment by jiacai2050** [comment]
![image](https://cloud.githubusercontent.com/assets/3848910/21610756/d7a2fe04-d204-11e6-82d4-cdd16a648c92.png)

Is this accurate ?

**Comment by weavejester** [comment]
No, sorry. The diagram should look more like:

```
 +---------------+
 |  Middleware   |
 |  +---------+  |             +---------+      +--------+
 |  |         |<-- request ----|         |      |        |
 |  | Handler |  |             | Adapter |<---->| Client |
 |  |         |--- response -->|         |      |        |
 |  +---------+  |             +---------+      +--------+
 +---------------+
```

The middleware should wrap the handler, and there's only one adapter per connection to the client. In more complicated setups you can combine multiple handlers, e.g. Compojure works by combining "routes" (handlers that can return nil), and middleware can be applied to individual routes, as well as the top-level handler.

**Comment by jiacai2050** [comment]
Oh, thanks. My understanding is almost the same as what your diagram express. 

The point I want to emphasize is that 

> Outmost middleware (middleware 3 in my diagram) will be the first to recevie the request, and the last to receive the response

**Comment by mpas** [comment]
Glad i struck this issue as my application did not work.. This due all the demos i see on the internet that totally ignore the content type. Is this now somewhere in the documentation?
