### ISSUE TITLE
[Security Issue] `X-XSS-Protection` header

### ISSUE THREAD

**Issue by mahsa2** [ring-clojure/ring-defaults#35]
Based on this [OWASP article](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#x-xss-protection-header), it is recommended to disable the `X-XSS-Protection` header by setting `X-XSS-Protection: 0` to avoid security issues in older browsers.

* Currently, the default is `:xss-protection {:enable? true, :mode :block}` at [this line](https://github.com/ring-clojure/ring-defaults/blob/4ecb31d97be116b3c177c651c013cd2834bb528a/src/ring/middleware/defaults.clj#L47).

* Also, setting `:xss-protection {:enable? false}` raises an error on the pre-condition check for `nil` at [this line](https://github.com/ring-clojure/ring-headers/blob/master/src/ring/middleware/x_headers.clj#L94), because the code sends an empty map [here](https://github.com/ring-clojure/ring-defaults/blob/master/src/ring/middleware/defaults.clj#L81) (`(dissoc options :enable?)` => `{}`).

I suggest updating [x-headers in the ring-headers repository](https://github.com/ring-clojure/ring-headers/blob/master/src/ring/middleware/x_headers.clj) to enforce this solution on all the dependent repositories. However, if you would prefer only fixing this repo, I can create a PR for it.

Thanks for your attention.

**Comment by weavejester** [comment]
Thanks for the issue report. I'd certainly welcome a PR to this repository to update the defaults, which I believe would be needed in either case. The x-headers functions should be marked as deprecated in their metadata, and a warning to STDERR added to their body. I think that's a better option than trying to silently fix an issue by changing behaviour.

**Comment by mahsa2** [comment]
Agreed with your suggested fix. It's better to raise awareness about this issue by raising error.
Made the PR for this repo.
